name: Assertions and static report

on:
  push:
    branches:
      - main
  workflow_dispatch:
# schedule:
#     - cron: '30 12 * * 1-5'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      # - name: Unlighthouse assertions and client
      #   run: unlighthouse-ci --site https://jpdiaz.dev/ --budget 75 --build-static

      - name: Run Unlighthouse Assertions for Site 1
        run: |
          mkdir -p reports/site1
          unlighthouse-ci --site https://jpdiaz.dev/ --budget 75 --build-static --output ./reports/site1

      - name: Run Unlighthouse Assertions for Site 2
        run: |
          mkdir -p reports/site2
          unlighthouse-ci --site https://miguediaz.com --budget 75 --build-static --output ./reports/site2

      # - name: Run Unlighthouse Assertions for Site 3
      #   run: |
      #     mkdir -p reports/site3
      #     unlighthouse-ci --site https://links.jpdiaz.dev/ --budget 75 --build-static --output ./reports/site3

      # - name: Run Unlighthouse Assertions for Site 4
      #   run: |
      #     mkdir -p reports/site4
      #     unlighthouse-ci --site https://docs.jpdiaz.dev/ --budget 75 --build-static --output ./reports/site4

      - name: Run Unlighthouse Assertions for Site 5
        run: |
          mkdir -p reports/site5
          unlighthouse-ci --site https://colombia.jpdiaz.dev/ --budget 75 --build-static --output ./reports/site5

      # - name: Run Unlighthouse Assertions for Site 6
      #   run: |
      #     mkdir -p reports/site6
      #     unlighthouse-ci --site https://freeforgeeks.com/#/ --budget 75 --build-static --output ./reports/site6

      - name: Deploy
        run: netlify deploy --dir=.unlighthouse --prod --message="New Release Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
